-- QL BAN SACH --
GO
	USE MASTER 
GO
	DROP DATABASE QLBANSACH
GO
	CREATE DATABASE QLBANSACH
GO
	USE QLBANSACH
GO
	CREATE TABLE NHANVIEN(
		ID INT IDENTITY PRIMARY KEY,
		MANV NVARCHAR(MAX),
		TEN NVARCHAR(MAX),
		NGAYSINH DATETIME,
		GIOITINH INT, -- 1: NAM, 0 : NU
		SDT NVARCHAR(MAX),
		DIACHI NVARCHAR(MAX),
		QUYEN INT,
		MATKHAU NVARCHAR(MAX),
		TAIKHOAN NVARCHAR(MAX)
	)
GO
	CREATE TABLE NXB(
		ID INT IDENTITY PRIMARY KEY,
		TENNXB NVARCHAR(MAX)
	)
GO
	CREATE TABLE SACH(
		ID INT IDENTITY PRIMARY KEY,
		MASACH NVARCHAR(MAX),
		TEN NVARCHAR(MAX),
		TACGIA NVARCHAR(MAX),
		GHICHU NVARCHAR(MAX),
		NXBID INT,
			FOREIGN KEY (NXBID) REFERENCES NXB(ID)
	)
GO
	CREATE TABLE KHO(
		ID INT IDENTITY PRIMARY KEY,
		SACHID INT,
			FOREIGN KEY (SACHID) REFERENCES SACH(ID),
		SOLUONG INT
	)
GO
	CREATE TABLE PHIEUNHAP(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		NGAY DATETIME,
		DIADIEM NVARCHAR(MAX),
		TONGTIEN INT
	)
GO
	CREATE TABLE CHITIETNHAP(
		ID INT IDENTITY PRIMARY KEY,
		PHIEUNHAPID INT,
			FOREIGN KEY (PHIEUNHAPID) REFERENCES PHIEUNHAP(ID),
		SACHID INT,
			FOREIGN KEY (SACHID) REFERENCES SACH(ID),
		SOLUONG INT,
		DONGIA INT,
		THANHTIEN INT
	)
GO
	CREATE TABLE HOADONBAN(
		ID INT IDENTITY PRIMARY KEY,
		NHANVIENID INT,
			FOREIGN KEY (NHANVIENID) REFERENCES NHANVIEN(ID),
		NGAY DATETIME,
		TONGTIEN INT
	)
GO
	CREATE TABLE CHITIETXUAT(
		ID INT IDENTITY PRIMARY KEY,
		HOADONBANID INT,
			FOREIGN KEY (HOADONBANID) REFERENCES HOADONBAN(ID),
		SACHID INT,
			FOREIGN KEY (SACHID) REFERENCES SACH(ID),
		SOLUONG INT,
		GIABAN INT,
		THANHTIEN INT
	)
GO
	-- THÊM DỮ LIỆU MẪU
	INSERT INTO NHANVIEN(MANV, TEN, NGAYSINH, GIOITINH, SDT, DIACHI, QUYEN, MATKHAU, TAIKHOAN) 
		VALUES('NV01',N'Phạm Thị Quỳnh', '8-30-1996', 0, '0912345678', N'Tam Hồng',1,'1', 'admin'),
		('NV02',N'Bùi Xuân Thủy', '9-3-1996', 1, '0912345678', N'Đồng Văn',0,'1','nv02') 
GO
	INSERT INTO NXB(TENNXB) VALUES(N'Nhi Đồng')
GO
